version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: test123
      MYSQL_PASSWORD: test123
      MYSQL_DB: todos
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: test123
      MYSQL_PASSWORD: test123
      MYSQL_DATABASE: todos
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root123 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

