apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-app-dev
  labels:
    app: todo-list-app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-list-app-dev
  template:
    metadata:
      labels:
        app: todo-list-app-dev
        env: dev
    spec:
      containers:
      - name: todo-list-app-dev
        image: emendoza96/app-todo-list:dev-v20
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: todo-list-service
spec:
  selector:
    app: todo-list-app-dev
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort