apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-app-prod
  labels:
    app: todo-list-app-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-list-app-prod
  template:
    metadata:
      labels:
        app: todo-list-app-prod
        env: prod
    spec:
      containers:
      - name: todo-list-app-prod
        image: emendoza96/app-todo-list:prod-v30
        ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: todo-list-service
spec:
  selector:
    app: todo-list-app-prod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort