apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-app-prod
  labels:
    app: todo-list-app-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-list-app-prod
  template:
    metadata:
      labels:
        app: todo-list-app-prod
        env: prod
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
    spec:
      containers:
      - name: todo-list-app-prod
        image: emendoza96/app-todo-list:prod-v54
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_HOST
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_PASSWORD
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: MYSQL_DB

---

apiVersion: v1
kind: Service
metadata:
  name: todo-list-service
spec:
  selector:
    app: todo-list-app-prod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort